/* Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms. */
// https://projecteuler.net/archives

#include <stdio.h>
#include <stdlib.h>

int main()
{
    long long i, *j, sum = 0; 
    j = (long long *) malloc((4E6 + 1)*sizeof(long long));
    j[1] = 1;
    j[2] = 2;

    for(i = 1; i < 4E6; i++)
    {          
        if(i > 2)
        {
            j[i] = j[i - 1] + j[i - 2];
        }
          
        if(j[i] >= 4E6)
        {
            break;
        }
        else if(j[i] % 2 == 0)
        {
            sum += (long long) j[i];
        }
    } 
    printf ("%lli \n", sum);
    free(j);
    j=NULL;
    return 0;
}